### PR TITLE
[v6] Delay checking unknown critical signature subpackets

### LINKED ISSUE #1765: Keys containing signatures with unknown critical subpackets are incorrectly rejected
When parsing a key, such as @dkg's public key:
<details>
<summary>public key</summary>

```
-----BEGIN PGP PUBLIC KEY BLOCK-----
Comment: D477 040C 70C2 156A 5C29  8549 BB7E 9101 495E 6BF7
Comment: <dkg@debian.org>
Comment: <dkg@fifthhorseman.net>

xjMEZXEJyxYJKwYBBAHaRw8BAQdA5BpbW0bpl5qCng/RiqwhQINrplDMSS5JsO/Y
O+5Zi7HCiQQfFgoAMQWCZadnIAUJBdtHCwMLCQcDFQoIApsBAh4BFiEE1HcEDHDC
FWpcKYVJu36RAUlea/cACgkQu36RAUlea/edDQD+M2QjnoEyu/TjI+gRXBpXQ5jC
snnp9FdYhaSSUW/vZ8kBAJByWljA9aMfVaVrmvgcYw7jzJz+gmZspBRB++5LZ20N
wsALBB8WCgB9BYJlcQnLAwsJBwkQu36RAUlea/dHFAAAAAAAHgAgc2FsdEBub3Rh
dGlvbnMuc2VxdW9pYS1wZ3Aub3Jn1AIHzfbck0sacYZhwNa+txoiOL+jUJq61lSz
gUSWLoUDFQoIApsBAh4BFiEE1HcEDHDCFWpcKYVJu36RAUlea/cAAJmhAP9zL2CT
MUHS4SBuFAzTFXdm7KL8HXE60XiYS2MhbpQa8AEA/4/0UvgF0CFbZHDvW5es2UwD
vcesn5DmW79IN3jcqwLNEDxka2dAZGViaWFuLm9yZz7CwBEEExYKAHkDCwkHRxQA
AAAAAB4AIHNhbHRAbm90YXRpb25zLnNlcXVvaWEtcGdwLm9yZ4l+Z3i19Uwjw3Cf
TNFCDjRsoufMoPOM7vM8HoOEdn/vAxUKCAKbAQIeARYhBNR3BAxwwhVqXCmFSbt+
kQFJXmv3BQJlp1+QBQkF2fBFAAoJELt+kQFJXmv36jAA/3dsXMSZPJSP6WaGui3s
tJCDer3f0wep3pOVR3+I8+B8AQDud/dXn9Y9MOGxzYvVyA9VwA17jaP8pkVYq5Ni
ye3TCsLACwQTFgoAfQWCZXEJywMLCQcJELt+kQFJXmv3RxQAAAAAAB4AIHNhbHRA
bm90YXRpb25zLnNlcXVvaWEtcGdwLm9yZ4l+Z3i19Uwjw3CfTNFCDjRsoufMoPOM
7vM8HoOEdn/vAxUKCAKbAQIeARYhBNR3BAxwwhVqXCmFSbt+kQFJXmv3AAALZQEA
hJsgouepQVV98BHUH6SvWvcKrb8dQEZOvHFbZQQPNWgA/A/DHkjYKnUkCg8Zc+Fo
nqOS/35sHhNA8CwqSQFrtN4KwsEABBYWCgFyBYJlw9DCCRC7fpEBSV5r90cUAAAA
AAAeACBzYWx0QG5vdGF0aW9ucy5zZXF1b2lhLXBncC5vcmcUs3g+jgk0FLXhqN/F
HvQ0onOXjo2fKHkpUENlDYxg6hYhBNR3BAxwwhVqXCmFSbt+kQFJXmv3wEGlFu5y
1ngdF5zkkA7A8gE09t7epA3HzV8I11WKEna2Qx8LwwOCIGftmDsfIereFFsYHW6b
SstDA6CqQ4+Ded+lgnN5M737ks3Yq67eXg+h9IQqBYezHlS7xXlqHQF2kzSUDL97
VB/BeEfH26fdmtW5udBZCaMHfXN26Drhm3hpc1LAxS8jEsNB9ODzJUR62hOr6CCM
D73LL9ADAA1fjvgJAbFgjGBhTjZ/PsddxnkXjdj1GO66QSZpY4jtzpfXuzyi3b6k
CYbOvAoCoLFvbT0o/ygrAj3HS7V1O5eC6ScO4s3wF1LS+tQnviw7NqlbacQGzCAX
ZjOQxyXI3BZNAeK8EgAAIJsBALlsVWngHNRplYgZ9ui19aZG3FbjHbEFtVY8uCOp
AR5dAQCecPjmlAF/bmzvFs58K+5BMos104JyLnuZGvf3+EwDAcLBcwQQAQoAHRYh
BKQNReyh8lYEbqqxETZQ0xCWIcOGBQJlw4i/AAoJEDZQ0xCWIcOG5cEQALDwlO/w
RMEAxQIv2c+pzDEHZeFirj2PK88xSWCfu7Gsv+v4fx+nMpDGCFqV40PUprFtgNPh
4+/MpOS1kqu4Ar8u5JAk7+V50YtFw6YxgbbwxNVMkaZkwEm+/7hBQthAjcceRXsR
M8+RNAheoPeiXzHjge8yyO91VAaqkiP9KeaE00SKqlH0bX3KSXxjW5rf72r27f/r
jNkIDnrGmWwD3/yEHUwi6hX1oOTIJumBvwcYWgUO31+XOyndWV4xq+b37Kv4GI6b
EQ3O1w4sp4InvGBXLfIenYisvDGKiPD1SCeWHEBp9IjonCqjpWHmmAgs4ig+MyC/
RHIBlb/Ncfrbt80TsQyEHJUgTgF3QVW534NkFAXOdluqPDdQu52f6OkHzZXY8yzC
Mwifuvc13vd5lGsB6c1YokCeuTiMTuWDVdkHjZ/PUVOlDIlpqYiI3CLOooanDLCv
6jQQDNcYwUFdKcaPklgLhx8TwKohwuhb8u+Kr5mjoxEEOylfmGZATnS3DM2m46Mz
sv4coV23AZkYylDXrMV49RgVwtmZXEyI3ApGP6iGBB2P7CFKCnKHUuo/BMwSYar7
fLsSPMreO8HlHWuvEF0pH6zW5KEol/10bbrWvfaf9AwwwUBd0YUNCfQBhhViZGQ3
shrA/RJUvSEgLKxGdUQQf8sXhyUEUjmvplr1wsFzBBABCgAdFiEEmi//dHmU4oe+
xCLxX0NADCHL+swFAmWmIecACgkQX0NADCHL+szzwA//RSxsrusOTiEgKD3iRCHw
TAA8WtB5j2keT1uVLVF5V8jPp6gR8IwzKJuA3FvDbcoahgLT8wQ8SIviGpa+Cb2I
4wT3qE2cA69AASHKl3s+lAJMXtxFWDFfbvm1v/2dNnqRV3w1NTwEj8nUU5ZjGBvJ
HUIwvWu7mgaBFJoe9vOrWxtcBmMb7G9mwfhoIGBSrDVcmOeGjlTSZjCfutveU8KL
cj0ci8qwMJTvr/HExr/BfSfJV4bZCYmgap5cr/kMoiToIoLrvCHpoiUHB3StXKGJ
d8ittjf4vdcrXIs12E5Bc3JAmp+vmmUBQDXRnfA7vT5HeFX9DMkuW9DW64S0dDm7
strzs7tirExbGQU98KOwZjnOo/bYSDYyaRbu7Kkl4TXin0n66Js3QFVLk1f7ALrK
JJsjsCF1KTqemJDUM8+iQph4CbLPzTTS8ddS2d4cWP+sdhwv7rGiYsvXCGGugqFd
yJWI3NIVMHz0R2HEFVOJnMPEbIDDRq1g2bhbR6XYDaIG1dx1gKwGyBYz61OhLrEa
ccgUMdpGNFbAEUwcCHmRC55ADhzb7TbZ5xHpYDE3QkcsVvGbpcNUf2CeEPgllGL6
xdevQ6TiHDIce3/YzrSSP04GzbmfBMHvWnOqGr5+OscCQogjcBmeGgshZHQpjeQG
CeGDCTmrWOVL9ljj3DbUI9HCdQQQFggAHRYhBLu2zUyY104TWKdSpgIpOm+k5TRz
BQJle1jYAAoJEAIpOm+k5TRzpDMA/0LbPvlXJZOyECGNg3CFa0c0x6eY5bn7SM3s
VSnDMnvpAQCoc9WztV6wRLS3z20otrcHbTC1+2rddKDCsuGNcIsqCMJ1BBAWCgAd
FiEE3hBnS+7+3i8euzdVXilOVFS9NA4FAmVyMAoACgkQXilOVFS9NA7wlQEA8Tig
jPfcACeSSZU3HxJ4kwhSHbi6ob71K7zcPJ8Ygs4BAMrIBEcRey61CPsU52J3Y8Dg
daD1H+qEAJ5hoq23lp8PzRc8ZGtnQGZpZnRoaG9yc2VtYW4ubmV0PsLAEQQTFgoA
eQMLCQdHFAAAAAAAHgAgc2FsdEBub3RhdGlvbnMuc2VxdW9pYS1wZ3Aub3JnEu/C
SCeyWwC6j4ihJr2u/z6delsF1pvYW3ufgf1L538DFQoIApsBAh4BFiEE1HcEDHDC
FWpcKYVJu36RAUlea/cFAmWnX5AFCQXZ8EUACgkQu36RAUlea/cjVwD+ONjdHM74
rAa6EEiiqaPjlptiaZxCVqFYXnib6EbZARkBAPnnR8pW8vCBnDXHKu65jNqwF3aH
761NaOqqMFfppg8GwsAKBBMWCgB9BYJlcQnLAwsJBwkQu36RAUlea/dHFAAAAAAA
HgAgc2FsdEBub3RhdGlvbnMuc2VxdW9pYS1wZ3Aub3JnEu/CSCeyWwC6j4ihJr2u
/z6delsF1pvYW3ufgf1L538DFQoIApsBAh4BFiEE1HcEDHDCFWpcKYVJu36RAUle
a/cAAC0WAPjCpxR9CXucYtA5wAQeHHxXQGDy/2i/waxjV6LUEQXAAP9zGbGYNI7T
+0D7Hil3nIi/OB8ZgdJPEpLRbDeHOO5kDsLBAAQWFgoBcgWCZcPQwgkQu36RAUle
a/dHFAAAAAAAHgAgc2FsdEBub3RhdGlvbnMuc2VxdW9pYS1wZ3Aub3Jny8CJb90p
FmSbNijzZh7crtJF1zWpZJOvMYocrPEMotsWIQTUdwQMcMIValwphUm7fpEBSV5r
98BBpRkj2jrLX0m93zt3hUDgWv0CPzgCJm8ZUUMZhdau4nQWpqTpWCK/2wTHV3Uf
Kb3OVxkLTytuFh2KVnwHqJDw/QNYPfBfvHYO9Afz4i6e6yJaWjyBA79V1YCexMh0
Ez0MpxzcX34Qyasag1NME8lcvefEO6XALho5IQudQJEjWhi3cwWt/ieOMiLGU56i
FtKXYRyISAiai2M/GLJ8Y59NQR6cvfO8vdfir07jrEJmYWD/XQEQUsgyjEFn06ZS
ZX0vNq/VXsmqbqSUAgSBRgNswZFtKTPcJNG7OEDMzTFaqrwQU0x9eoisNlQDIN8u
qN8+YUN/clQGjZ6ivi46W7A+pngAAHsmAP9/rVW4esJVtXeU2RNgo+rsPVENbOYY
IPF5TdLAtyK2oAEA485PermnUnM5gsqeyiF4XTPtZ3mRSDMs89HoEfOm+gLCwXME
EAEKAB0WIQSkDUXsofJWBG6qsRE2UNMQliHDhgUCZcOIuwAKCRA2UNMQliHDhq3d
EACIxwvNIlW6UkZQGQcwkGNbTxhhTmRwH/R/Ks098On4iF58LDjZXaJzEy+o307G
/y68AWqTYgJzikEkgtz/Ua01z0zxjSUxc5VY8p7719z1Zfh43GAM1TVNiCk7MqZA
jWFE2qCuny6EwUMedWUWiMhbzphCBwnAcEc7B9TDhVLfT9CNZvahxUkcoDOdEtK9
HK7fQ94zOJsD2LLQKq35pp9b8pRXlQsg0cAGdtppVe0RrVx9J4w1qp/cPdhQAB7w
1Se5Rmrh67RS2dpseKRAcsnuL2wIk95c1TRI8RfFjmLcVHMMnvBS0cM2n8ytbu1f
HPk4z9iiZrGUzRw/SCOX858ICPAXsvf9CYAkJlzyhHwsrnCL2/MNtRSwMWocGag3
N+wToHUKb9Y5chW2AqvQsOiG76JrsrIAlj9y5BhuDenbCVKJG/Qem8CjGko0Dgro
EHB0dPtzYg/BcBM49bpfaUD9nCR2VoxntYnYrXwtT6c92Zj881kT3dR21x5BdS4j
5JiVOc0DXtbll7zQuXy3XMtQfxSAS9S9J0wBnLpvODM3vd4Z3ZzJahPUrVi6SO1t
Lkx/E1Jjf08EvATb8xFVxvW1LHUT2bXoUqfIbgHkvoE9ZTDbvTbsV19X05vXk/MH
qRjaZFJKrpVc+rInSmZARP2drPtn0fqbnlwBz5kQLwacr8LBcwQQAQoAHRYhBJov
/3R5lOKHvsQi8V9DQAwhy/rMBQJlpiHnAAoJEF9DQAwhy/rMTHYP+gPr21vrurbD
2OmADAjCN4TqELAocsO7dlCAYz9z9z9CKemPtQLxVcpiE1SqURP655la4noy7S5q
4QDQgo5vHfsLHh9xjNEjyL9V+wCmwL+nWWOCUjkx6xxES6NqVK6FufyyvVLQcd0Y
XE0RGno4FXnhl8xkIPKD0alvtgtnfTAzG1CXSz/su91VaMDeyYonqVP0Qy4hsd7a
N+XVI3ZaJIDFz+DaFPHBi9V6jj13xdO9Ver5gqCz/x0+/LUVs6HUr1cyemtmp95d
8DQIkfpQq+RX0i/5JFmcxZGydAi4obWVUCF7yq5ywTpJnJEiDEcgAaZxguZCZDy2
utDMLo6rs251LNk3MxSK+Y/fiHYV6Pd/b0+Y//9XmGw7jJHKKYUkDWq+cK455ZBA
nZCt+JvZHRKdCgkgZoymHdnNNnRqMvZtmATapCSnIPJohCNGM2Z2oX7N5CI7BZXh
ePJrslmBWrFBBh62IGtqfpmMKA/Q/c3dV5izISCpeCvG8LDyoA9h7R8HMiMQGrJC
eGctB28coZKD1Diwbktq6iSH8Po/QY3vvVWbbdXD+wFOyEZWY4OQWuhDBJsBaRQf
GTPkhdKSUcLmaiRpC9ls1ucxDhSm4VuHDIYBHESGgn0X7npZD2HtwqVq/0Atk9w0
RpJWYJViD37hm8KVYYzmsQ+ZE+J8XvPWwnUEEBYIAB0WIQS7ts1MmNdOE1inUqYC
KTpvpOU0cwUCZXtY2AAKCRACKTpvpOU0czHjAQC9hMNcr5deC0+o/eaYiKrjCMWb
mfR4lkHzL2VJwdwlKwEAtMz8l7CAAJo09UqTdy/4JsH05EkFtEFkRMr1191FwwPC
dQQQFgoAHRYhBN4QZ0vu/t4vHrs3VV4pTlRUvTQOBQJlcjAKAAoJEF4pTlRUvTQO
4FQBAJZkMcAxpa6bX12eYyEQ+xQSUKOtEpKhKUDqdgxFyNR5AQCVlV1b3MAIoEhq
IqDHEecy6myoffIcu3UGtUhgy6m3Bc4zBGVxCcsWCSsGAQQB2kcPAQEHQI19uRat
kPSFBXh8usgciEDwZxTnnRZYrhIgiFMybBDQwsDFBBgWCgEtRxQAAAAAAB4AIHNh
bHRAbm90YXRpb25zLnNlcXVvaWEtcGdwLm9yZ8KilrMOerqFlSyBXLO2XnCYMKbE
jXr1gs274ikPMkS1ApsCvqAEGRYKAG8FgmVxCcsJEHctFh41zUuBRxQAAAAAAB4A
IHNhbHRAbm90YXRpb25zLnNlcXVvaWEtcGdwLm9yZxCCUjsbsNsv1CZoOTNwS6Td
CWIzg2aV4hFRbtW8gEczFiEEdLwExD2GCEvoZywGdy0WHjXNS4EAALB/AQCoNQuS
yvw+6UpFwg/o300j/gqjOfIhy44eLyoaTirEyQEAh5XbRI8SdZLD0xYBvR4oRx+6
nOv8L7y8O+xEzKcJawMWIQTUdwQMcMIValwphUm7fpEBSV5r9wUCZadfqwUJAheJ
YAAKCRC7fpEBSV5r98nbAP9q6EGdiZv+4lK4P9guQpVgP8W7zwt9S8jJBhh9v66v
LQD/QYKi7gj5zU1T6nl/fvaqjJmhau8Jr46uSPssnAMPQg3CwL8EGBYKATEFgmVx
CcsJELt+kQFJXmv3RxQAAAAAAB4AIHNhbHRAbm90YXRpb25zLnNlcXVvaWEtcGdw
Lm9yZ8KilrMOerqFlSyBXLO2XnCYMKbEjXr1gs274ikPMkS1ApsCvqAEGRYKAG8F
gmVxCcsJEHctFh41zUuBRxQAAAAAAB4AIHNhbHRAbm90YXRpb25zLnNlcXVvaWEt
cGdwLm9yZxCCUjsbsNsv1CZoOTNwS6TdCWIzg2aV4hFRbtW8gEczFiEEdLwExD2G
CEvoZywGdy0WHjXNS4EAALB/AQCoNQuSyvw+6UpFwg/o300j/gqjOfIhy44eLyoa
TirEyQEAh5XbRI8SdZLD0xYBvR4oRx+6nOv8L7y8O+xEzKcJawMWIQTUdwQMcMIV
alwphUm7fpEBSV5r9wAAUPUA/RiwTcR6KDW2RZp7Ku+8x/kqXW23Yt6RM1YOcH4V
Qb1KAP4pry989HzC5XwPfLlj1Cr3EY75CQQEJbRTWo3KmDrlAc44BGVxCcsSCisG
AQQBl1UBBQEBB0BZMsRrRaaeFSYMF1ZdfRmVgBriDUIr99eDQ085BK14DgMBCAfC
wAYEGBYKAG5HFAAAAAAAHgAgc2FsdEBub3RhdGlvbnMuc2VxdW9pYS1wZ3Aub3Jn
sazAWXtEHUPmSTmcRZAIsAsNiO8k0hdjsfRlRVipgJgCmwwWIQTUdwQMcMIValwp
hUm7fpEBSV5r9wUCZadfqwUJAheJYAAKCRC7fpEBSV5r90AjAPwLgY1iKiFJEj32
SVD5f721929l79VxQB5FlQssx1n5kQEA6Uct2tPvbB6T7p5KG3Gl+tbi7oJAuxFm
pkpW5/N2OwjCwAAEGBYKAHIFgmVxCcsJELt+kQFJXmv3RxQAAAAAAB4AIHNhbHRA
bm90YXRpb25zLnNlcXVvaWEtcGdwLm9yZ7GswFl7RB1D5kk5nEWQCLALDYjvJNIX
Y7H0ZUVYqYCYApsMFiEE1HcEDHDCFWpcKYVJu36RAUlea/cAAFwlAP9/iW2lK8sE
4ESH8LZ0hhp2BK6qQKqrQHhY6EVGRYlmVwD8DGotYbijxSuubCuYzjYWGDEq0RfA
JIcTTS7zBHhSnwY=
=MTdj
-----END PGP PUBLIC KEY BLOCK-----
```

</details>

we throw `Error: Unknown signature subpacket type 37`, even though the signature is in an unused (and unknown) signature packet, which is not required to validate the key. Therefore, we should change this error to an `UnsupportedError` (so that it doesn't cause us to reject the entire key), or reject the signature during validation instead of during parsing.

### PR DESCRIPTION
**Pull request by twiss**
Throw when verifying signatures with unknown critical subpackets, instead of when parsing them.

Fixes #1765.

### CODE REVIEW

File: src/packet/signature.js [hunk 1]
```diff
@@ -801,6 +801,11 @@ class SignaturePacket {
       [enums.signature.binary, enums.signature.text].includes(this.signatureType)) {
       throw new Error('Insecure message hash algorithm: ' + enums.read(enums.hash, this.hashAlgorithm).toUpperCase());
     }
+    this.unknownSubpackets.forEach(({ type, critical }) => {
+      if (critical) {
+        throw new Error(`Unknown signature subpacket type ${type}`);
```
Comment (larabr) [inline src/packet/signature.js:806]:
```suggestion
        throw new Error(`Unknown critical signature subpacket type ${type}`);
```

**Review by larabr — APPROVED** [review]
